builders:
  rxBlocGenerator:
    import: "package:rx_bloc_generator/builder.dart"
    builder_factories: ["rxBlocGenerator"]
    build_extensions: {'.dart': ['.g.dart']}
    auto_apply: all_packages
    build_to: source