name: rx_bloc
description: A Flutter package that helps implementing the BLoC (Business Logic Component) Design Pattern using the power of reactive streams.
version: 0.0.1
repository: https://github.com/Prime-Holding/RxBloc
issue_tracker: https://github.com/Prime-Holding/RxBloc/issues
homepage: https://www.primeholding.com/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  #assets:
  # - images/a_dot_burr.jpeg