name: {{project_name}}
description: A new Flutter project.
homepage: https://{{organization_name}}.{{domain_name}}
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.0.1
  cupertino_icons: ^1.0.3
  dio: ^4.0.0{{#analytics}}
  firebase_analytics: ^8.3.2{{/analytics}}{{#uses_firebase}}
  firebase_core: ^1.6.0{{/uses_firebase}}{{#push_notifications}}
  firebase_messaging: ^10.0.7{{/push_notifications}}
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^4.0.0
  flutter_secure_storage: ^4.2.1
  golden_toolkit: ^0.11.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  provider: ^6.0.0
  retrofit: ^2.0.1
  rx_bloc: ^3.2.0
  rx_bloc_list: ^3.1.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8

  # Server related packages
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  shelf_static: ^1.1.0

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.2
  # flutter_driver:
  #   sdk: flutter
  flutter_lints: any
  flutter_test:
    sdk: flutter
  http: ^0.13.3 # This package is used for the local server (if not used, can be removed)
  mockito: ^5.0.16
  retrofit_generator: ^2.0.1
  rx_bloc_generator: ^5.1.0
  rx_bloc_test: any
  test: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500