name: rx_bloc_test
description: A Flutter package with the goal to enable testing rxBlocs from the FlutterRxBloc package with ease.
version: 0.0.5
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_test
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://primeholding.com

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  test: ^1.15.2
  meta: ^1.1.8
  rx_bloc: ^1.0.1
  mockito: ^4.1.3
  rxdart: ^0.24.1
  quiver: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
