name: rx_bloc_test
description: A Flutter package with the goal to enable testing rxBlocs from the FlutterRxBloc package with ease.
version: 1.0.0
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_test
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://primeholding.com

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  test: ^1.15.2
  rx_bloc: ^1.0.4
  rxdart: ^0.24.1
  meta: ^1.1.8
  mockito: ^4.1.3
  quiver: ^2.1.5

dev_dependencies:
  coverage: ^0.14.1
  pedantic: ^1.9.0
