name: rx_bloc_generator
description: Code generator for rx_bloc that makes your BloC zero-boilerplate.
version: 6.0.1
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_generator
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://www.primeholding.com/

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  analyzer: ^5.10.0
  build: ^2.3.1
  code_builder: ^4.4.0
  collection: ^1.17.0
  dart_style: ">=2.3.0 <3.0.0"
  logging: ^1.1.1
  rx_bloc: ^4.0.1
  source_gen: ">=1.2.7 <2.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  clean_coverage: ^0.0.3
  coverage: ^1.6.3
  flutter_lints: ^2.0.1
  source_gen_test: ^1.0.4
  test: ^1.24.1
