name: github_search
description: Example project showcasing the github search functionality with use of public api
homepage: https://primeholding.com/
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  auto_route: ^7.7.1
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  dio: ^5.3.0
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.6.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: any
  flutter_secure_storage: ^8.0.0
  golden_toolkit: ^0.15.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.0
  provider: ^6.0.3
  retrofit: ^4.0.1
  rx_bloc: any
  rx_bloc_list: any
  rxdart: ^0.27.3
  shared_preferences: ^2.0.11

  # Only for testing purposes
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  # flutter_driver:
  #   sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

  retrofit_generator: ^7.0.8
  rx_bloc_generator: any
  rx_bloc_test: any
  test: any


dependency_overrides:
  flutter_rx_bloc:
    path: ../../packages/flutter_rx_bloc
  rx_bloc:
    path: ../../packages/rx_bloc
  rx_bloc_generator:
    path: ../../packages/rx_bloc_generator
  rx_bloc_list:
    path: ../../packages/rx_bloc_list
  rx_bloc_test:
    path: ../../packages/rx_bloc_test

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

