name: "Test and build app"

# Define events when this workflow is triggered
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/test_and_build_app.yaml"
      - ".github/workflows/fastlane_android_custom_build_and_deploy.yaml"
      - ".github/workflows/fastlane_ios_custom_build_and_deploy.yaml"
      
  pull_request:
    paths:
      - ".github/workflows/test_and_build_app.yaml"
      - ".github/workflows/fastlane_android_custom_build_and_deploy.yaml"
      - ".github/workflows/fastlane_ios_custom_build_and_deploy.yaml"

# Example of a fastlane custom build
jobs:
  build_android_app:
    uses: ./.github/workflows/fastlane_android_custom_build_and_deploy.yaml
    with:
      build_name: 1.0.0
      build_number: 1
    secrets:
      mobile_distribution_encryption_password: ${{ secrets.MOBILE_DISTRIBUTION_ENCRYPTION_PASSWORD }}
      mobile_distribution_repository_access_secret: ${{ secrets.MOBILE_DISTRIBUTION_REPOSITORY_ACCESS_SECRET }}
  
  build_ios_app:
    uses: ./.github/workflows/fastlane_ios_custom_build_and_deploy.yaml
    with:
      build_name: 1.0.0
      build_number: 1
    secrets:
      mobile_distribution_encryption_password: ${{ secrets.MOBILE_DISTRIBUTION_ENCRYPTION_PASSWORD }}
      mobile_distribution_repository_access_secret: ${{ secrets.MOBILE_DISTRIBUTION_REPOSITORY_ACCESS_SECRET }}
