name: rx_bloc_cli
description: Rx Bloc Command Line Interface
version: 0.0.1
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc_cli
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://www.primeholding.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^1.6.0
  io: ^0.3.4
  mason: ^0.0.1-dev.27
  path: ^1.8.0

dev_dependencies:

executables:
  rx_bloc_cli: