name: rx_bloc_test
description: A Flutter package with the goal to enable testing rxBlocs from the FlutterRxBloc package with ease.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  test: ^1.3.0
  meta: ^1.1.6
  rx_bloc: ^0.0.1
  mockito: ^4.0.0
  rxdart: ^0.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.primeholding.rx_bloc_test
    pluginClass: RxBlocTestPlugin

  #assets:
  # - images/a_dot_burr.jpeg

