name: flutter_examples

on:
  push:
    paths:
      - ".github/workflows/examples.yaml"
      - "packages/**"
      - "examples/**"

  pull_request:
    paths:
      - ".github/workflows/flutter_examples.yaml"
      - "packages/**"
      - "examples/**"

jobs:
  examples:
    strategy:
      matrix:
        folder:
          [
            "examples/counter",
            "examples/division",
            "examples/favorites_advanced/rx_bloc_favorites_advanced",
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - name: Install Dependencies
        working-directory: ${{ matrix.folder }}
        run: flutter packages get
      - name: Analyze
        working-directory: ${{ matrix.folder }}
        run: flutter analyze lib
      - name: Run tests
        working-directory: ${{ matrix.folder }}
        run: |
          if [ -d "test" ]; then
            flutter test
          fi
  build:
    needs: [examples]
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'